resources:
- ../cluster-template.yaml
- ../bases/crs-cni.yaml
patches:
- patch: |-
    kind: Cluster
    apiVersion: cluster.x-k8s.io/v1alpha4
    metadata:
      name: not-used
      labels:
        cni: "${CLUSTER_NAME}-crs-cni"
  target:
    kind: Cluster
