---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/packethost/cluster-api-provider-packet

steps:
- name: test
  pull: always
  image: golang:1.14.2-alpine3.11
  environment:
    CGO_ENABLED: 0
  commands:
  - apk --update add make git bash jq curl
  - make kubebuilder
  - make test

- name: image
  pull: always
  image: plugins/docker
  settings:
    dry_run: true
    context: .
    dockerfile: Dockerfile
    repo: packethost/cluster-api-provider-packet
    tags:
    - latest
    build_args:
      - GOVER=1.14.2-alpine3.11

- name: publish
  pull: always
  image: plugins/docker
  settings:
    context: .
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: packethost/cluster-api-provider-packet
    tags:
    - "${DRONE_COMMIT}"
    - latest
    username:
      from_secret: docker_username
  when:
    branch: master
    event:
      - push
      - tag
