before:
  hooks:
    - make manifest
builds:
  -
    id: capp
    env:
      - CGO_ENABLED=0
    binary: manager
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  extra_files:
    - glob: "./out/release/infrastructure-packet/v*/*"
dockers:
  - image_templates:
      - "packethost/cluster-api-provider-packet:latest-arm64"
      - "packethost/cluster-api-provider-packet:{{ .Tag }}-arm64"
    binaries:
      - manager
    builds:
      - capp
    dockerfile: Dockerfile-arm64.goreleaser
    goos: linux
    goarch: arm64
  - image_templates:
      - "packethost/cluster-api-provider-packet:latest-amd64"
      - "packethost/cluster-api-provider-packet:{{ .Tag }}-amd64"
    dockerfile: Dockerfile-amd64.goreleaser
    binaries:
      - manager
    builds:
      - capp
    goos: linux
    goarch: amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
