/*
Load Balancer Management API

Load Balancer Management API is an API for managing load balancers.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// LoadBalancerPoolOriginPortNumber - Listening port of the origin
type LoadBalancerPoolOriginPortNumber struct {
	Int32 *int32
}

// int32AsLoadBalancerPoolOriginPortNumber is a convenience function that returns int32 wrapped in LoadBalancerPoolOriginPortNumber
func Int32AsLoadBalancerPoolOriginPortNumber(v *int32) LoadBalancerPoolOriginPortNumber {
	return LoadBalancerPoolOriginPortNumber{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *LoadBalancerPoolOriginPortNumber) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(LoadBalancerPoolOriginPortNumber)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(LoadBalancerPoolOriginPortNumber)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LoadBalancerPoolOriginPortNumber) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *LoadBalancerPoolOriginPortNumber) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableLoadBalancerPoolOriginPortNumber struct {
	value *LoadBalancerPoolOriginPortNumber
	isSet bool
}

func (v NullableLoadBalancerPoolOriginPortNumber) Get() *LoadBalancerPoolOriginPortNumber {
	return v.value
}

func (v *NullableLoadBalancerPoolOriginPortNumber) Set(val *LoadBalancerPoolOriginPortNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadBalancerPoolOriginPortNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadBalancerPoolOriginPortNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadBalancerPoolOriginPortNumber(val *LoadBalancerPoolOriginPortNumber) *NullableLoadBalancerPoolOriginPortNumber {
	return &NullableLoadBalancerPoolOriginPortNumber{value: val, isSet: true}
}

func (v NullableLoadBalancerPoolOriginPortNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadBalancerPoolOriginPortNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
