// +build !ignore_autogenerated_core_v1alpha3

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.21.3. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha4 "sigs.k8s.io/cluster-api-provider-packet/api/v1alpha4"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PacketCluster)(nil), (*v1alpha4.PacketCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketCluster_To_v1alpha4_PacketCluster(a.(*PacketCluster), b.(*v1alpha4.PacketCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketCluster)(nil), (*PacketCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketCluster_To_v1alpha3_PacketCluster(a.(*v1alpha4.PacketCluster), b.(*PacketCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketClusterList)(nil), (*v1alpha4.PacketClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketClusterList_To_v1alpha4_PacketClusterList(a.(*PacketClusterList), b.(*v1alpha4.PacketClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketClusterList)(nil), (*PacketClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketClusterList_To_v1alpha3_PacketClusterList(a.(*v1alpha4.PacketClusterList), b.(*PacketClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketClusterSpec)(nil), (*v1alpha4.PacketClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketClusterSpec_To_v1alpha4_PacketClusterSpec(a.(*PacketClusterSpec), b.(*v1alpha4.PacketClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketClusterSpec)(nil), (*PacketClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(a.(*v1alpha4.PacketClusterSpec), b.(*PacketClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketClusterStatus)(nil), (*v1alpha4.PacketClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketClusterStatus_To_v1alpha4_PacketClusterStatus(a.(*PacketClusterStatus), b.(*v1alpha4.PacketClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachine)(nil), (*v1alpha4.PacketMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachine_To_v1alpha4_PacketMachine(a.(*PacketMachine), b.(*v1alpha4.PacketMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketMachine)(nil), (*PacketMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachine_To_v1alpha3_PacketMachine(a.(*v1alpha4.PacketMachine), b.(*PacketMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineList)(nil), (*v1alpha4.PacketMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineList_To_v1alpha4_PacketMachineList(a.(*PacketMachineList), b.(*v1alpha4.PacketMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketMachineList)(nil), (*PacketMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineList_To_v1alpha3_PacketMachineList(a.(*v1alpha4.PacketMachineList), b.(*PacketMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplate)(nil), (*v1alpha4.PacketMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplate_To_v1alpha4_PacketMachineTemplate(a.(*PacketMachineTemplate), b.(*v1alpha4.PacketMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketMachineTemplate)(nil), (*PacketMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(a.(*v1alpha4.PacketMachineTemplate), b.(*PacketMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplateList)(nil), (*v1alpha4.PacketMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplateList_To_v1alpha4_PacketMachineTemplateList(a.(*PacketMachineTemplateList), b.(*v1alpha4.PacketMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketMachineTemplateList)(nil), (*PacketMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(a.(*v1alpha4.PacketMachineTemplateList), b.(*PacketMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplateResource)(nil), (*v1alpha4.PacketMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplateResource_To_v1alpha4_PacketMachineTemplateResource(a.(*PacketMachineTemplateResource), b.(*v1alpha4.PacketMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketMachineTemplateResource)(nil), (*PacketMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(a.(*v1alpha4.PacketMachineTemplateResource), b.(*PacketMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplateSpec)(nil), (*v1alpha4.PacketMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplateSpec_To_v1alpha4_PacketMachineTemplateSpec(a.(*PacketMachineTemplateSpec), b.(*v1alpha4.PacketMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PacketMachineTemplateSpec)(nil), (*PacketMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(a.(*v1alpha4.PacketMachineTemplateSpec), b.(*PacketMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha3.APIEndpoint)(nil), (*apiv1alpha4.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*apiv1alpha3.APIEndpoint), b.(*apiv1alpha4.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*PacketMachineSpec)(nil), (*v1alpha4.PacketMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineSpec_To_v1alpha4_PacketMachineSpec(a.(*PacketMachineSpec), b.(*v1alpha4.PacketMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*PacketMachineStatus)(nil), (*v1alpha4.PacketMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineStatus_To_v1alpha4_PacketMachineStatus(a.(*PacketMachineStatus), b.(*v1alpha4.PacketMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha4.APIEndpoint)(nil), (*apiv1alpha3.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*apiv1alpha4.APIEndpoint), b.(*apiv1alpha3.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.PacketClusterStatus)(nil), (*PacketClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketClusterStatus_To_v1alpha3_PacketClusterStatus(a.(*v1alpha4.PacketClusterStatus), b.(*PacketClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.PacketMachineSpec)(nil), (*PacketMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(a.(*v1alpha4.PacketMachineSpec), b.(*PacketMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.PacketMachineStatus)(nil), (*PacketMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PacketMachineStatus_To_v1alpha3_PacketMachineStatus(a.(*v1alpha4.PacketMachineStatus), b.(*PacketMachineStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_PacketCluster_To_v1alpha4_PacketCluster(in *PacketCluster, out *v1alpha4.PacketCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_PacketClusterSpec_To_v1alpha4_PacketClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_PacketClusterStatus_To_v1alpha4_PacketClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketCluster_To_v1alpha4_PacketCluster is an autogenerated conversion function.
func Convert_v1alpha3_PacketCluster_To_v1alpha4_PacketCluster(in *PacketCluster, out *v1alpha4.PacketCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketCluster_To_v1alpha4_PacketCluster(in, out, s)
}

func autoConvert_v1alpha4_PacketCluster_To_v1alpha3_PacketCluster(in *v1alpha4.PacketCluster, out *PacketCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_PacketClusterStatus_To_v1alpha3_PacketClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_PacketCluster_To_v1alpha3_PacketCluster is an autogenerated conversion function.
func Convert_v1alpha4_PacketCluster_To_v1alpha3_PacketCluster(in *v1alpha4.PacketCluster, out *PacketCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketCluster_To_v1alpha3_PacketCluster(in, out, s)
}

func autoConvert_v1alpha3_PacketClusterList_To_v1alpha4_PacketClusterList(in *PacketClusterList, out *v1alpha4.PacketClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.PacketCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_PacketCluster_To_v1alpha4_PacketCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_PacketClusterList_To_v1alpha4_PacketClusterList is an autogenerated conversion function.
func Convert_v1alpha3_PacketClusterList_To_v1alpha4_PacketClusterList(in *PacketClusterList, out *v1alpha4.PacketClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketClusterList_To_v1alpha4_PacketClusterList(in, out, s)
}

func autoConvert_v1alpha4_PacketClusterList_To_v1alpha3_PacketClusterList(in *v1alpha4.PacketClusterList, out *PacketClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacketCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_PacketCluster_To_v1alpha3_PacketCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_PacketClusterList_To_v1alpha3_PacketClusterList is an autogenerated conversion function.
func Convert_v1alpha4_PacketClusterList_To_v1alpha3_PacketClusterList(in *v1alpha4.PacketClusterList, out *PacketClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketClusterList_To_v1alpha3_PacketClusterList(in, out, s)
}

func autoConvert_v1alpha3_PacketClusterSpec_To_v1alpha4_PacketClusterSpec(in *PacketClusterSpec, out *v1alpha4.PacketClusterSpec, s conversion.Scope) error {
	out.ProjectID = in.ProjectID
	out.Facility = in.Facility
	if err := Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketClusterSpec_To_v1alpha4_PacketClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_PacketClusterSpec_To_v1alpha4_PacketClusterSpec(in *PacketClusterSpec, out *v1alpha4.PacketClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketClusterSpec_To_v1alpha4_PacketClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(in *v1alpha4.PacketClusterSpec, out *PacketClusterSpec, s conversion.Scope) error {
	out.ProjectID = in.ProjectID
	out.Facility = in.Facility
	if err := Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_PacketClusterSpec_To_v1alpha3_PacketClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(in *v1alpha4.PacketClusterSpec, out *PacketClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_PacketClusterStatus_To_v1alpha4_PacketClusterStatus(in *PacketClusterStatus, out *v1alpha4.PacketClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha3_PacketClusterStatus_To_v1alpha4_PacketClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_PacketClusterStatus_To_v1alpha4_PacketClusterStatus(in *PacketClusterStatus, out *v1alpha4.PacketClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketClusterStatus_To_v1alpha4_PacketClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_PacketClusterStatus_To_v1alpha3_PacketClusterStatus(in *v1alpha4.PacketClusterStatus, out *PacketClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	// WARNING: in.Conditions requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_PacketMachine_To_v1alpha4_PacketMachine(in *PacketMachine, out *v1alpha4.PacketMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_PacketMachineSpec_To_v1alpha4_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_PacketMachineStatus_To_v1alpha4_PacketMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachine_To_v1alpha4_PacketMachine is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachine_To_v1alpha4_PacketMachine(in *PacketMachine, out *v1alpha4.PacketMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachine_To_v1alpha4_PacketMachine(in, out, s)
}

func autoConvert_v1alpha4_PacketMachine_To_v1alpha3_PacketMachine(in *v1alpha4.PacketMachine, out *PacketMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_PacketMachineStatus_To_v1alpha3_PacketMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_PacketMachine_To_v1alpha3_PacketMachine is an autogenerated conversion function.
func Convert_v1alpha4_PacketMachine_To_v1alpha3_PacketMachine(in *v1alpha4.PacketMachine, out *PacketMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketMachine_To_v1alpha3_PacketMachine(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineList_To_v1alpha4_PacketMachineList(in *PacketMachineList, out *v1alpha4.PacketMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.PacketMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_PacketMachine_To_v1alpha4_PacketMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_PacketMachineList_To_v1alpha4_PacketMachineList is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineList_To_v1alpha4_PacketMachineList(in *PacketMachineList, out *v1alpha4.PacketMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineList_To_v1alpha4_PacketMachineList(in, out, s)
}

func autoConvert_v1alpha4_PacketMachineList_To_v1alpha3_PacketMachineList(in *v1alpha4.PacketMachineList, out *PacketMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacketMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_PacketMachine_To_v1alpha3_PacketMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_PacketMachineList_To_v1alpha3_PacketMachineList is an autogenerated conversion function.
func Convert_v1alpha4_PacketMachineList_To_v1alpha3_PacketMachineList(in *v1alpha4.PacketMachineList, out *PacketMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketMachineList_To_v1alpha3_PacketMachineList(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineSpec_To_v1alpha4_PacketMachineSpec(in *PacketMachineSpec, out *v1alpha4.PacketMachineSpec, s conversion.Scope) error {
	out.OS = in.OS
	out.BillingCycle = in.BillingCycle
	out.MachineType = in.MachineType
	// WARNING: in.SshKeys requires manual conversion: does not exist in peer-type
	out.Facility = in.Facility
	out.IPXEUrl = in.IPXEUrl
	out.HardwareReservationID = in.HardwareReservationID
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.Tags = *(*v1alpha4.Tags)(unsafe.Pointer(&in.Tags))
	return nil
}

func autoConvert_v1alpha4_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(in *v1alpha4.PacketMachineSpec, out *PacketMachineSpec, s conversion.Scope) error {
	out.OS = in.OS
	out.BillingCycle = in.BillingCycle
	out.MachineType = in.MachineType
	// WARNING: in.SSHKeys requires manual conversion: does not exist in peer-type
	out.Facility = in.Facility
	out.IPXEUrl = in.IPXEUrl
	out.HardwareReservationID = in.HardwareReservationID
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.Tags = *(*Tags)(unsafe.Pointer(&in.Tags))
	return nil
}

func autoConvert_v1alpha3_PacketMachineStatus_To_v1alpha4_PacketMachineStatus(in *PacketMachineStatus, out *v1alpha4.PacketMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*v1alpha4.PacketResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha4_PacketMachineStatus_To_v1alpha3_PacketMachineStatus(in *v1alpha4.PacketMachineStatus, out *PacketMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*PacketResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	// WARNING: in.Conditions requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_PacketMachineTemplate_To_v1alpha4_PacketMachineTemplate(in *PacketMachineTemplate, out *v1alpha4.PacketMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_PacketMachineTemplateSpec_To_v1alpha4_PacketMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplate_To_v1alpha4_PacketMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplate_To_v1alpha4_PacketMachineTemplate(in *PacketMachineTemplate, out *v1alpha4.PacketMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplate_To_v1alpha4_PacketMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(in *v1alpha4.PacketMachineTemplate, out *PacketMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(in *v1alpha4.PacketMachineTemplate, out *PacketMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineTemplateList_To_v1alpha4_PacketMachineTemplateList(in *PacketMachineTemplateList, out *v1alpha4.PacketMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.PacketMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_PacketMachineTemplate_To_v1alpha4_PacketMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplateList_To_v1alpha4_PacketMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplateList_To_v1alpha4_PacketMachineTemplateList(in *PacketMachineTemplateList, out *v1alpha4.PacketMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplateList_To_v1alpha4_PacketMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(in *v1alpha4.PacketMachineTemplateList, out *PacketMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacketMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(in *v1alpha4.PacketMachineTemplateList, out *PacketMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineTemplateResource_To_v1alpha4_PacketMachineTemplateResource(in *PacketMachineTemplateResource, out *v1alpha4.PacketMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_PacketMachineSpec_To_v1alpha4_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplateResource_To_v1alpha4_PacketMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplateResource_To_v1alpha4_PacketMachineTemplateResource(in *PacketMachineTemplateResource, out *v1alpha4.PacketMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplateResource_To_v1alpha4_PacketMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(in *v1alpha4.PacketMachineTemplateResource, out *PacketMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(in *v1alpha4.PacketMachineTemplateResource, out *PacketMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineTemplateSpec_To_v1alpha4_PacketMachineTemplateSpec(in *PacketMachineTemplateSpec, out *v1alpha4.PacketMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_PacketMachineTemplateResource_To_v1alpha4_PacketMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplateSpec_To_v1alpha4_PacketMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplateSpec_To_v1alpha4_PacketMachineTemplateSpec(in *PacketMachineTemplateSpec, out *v1alpha4.PacketMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplateSpec_To_v1alpha4_PacketMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(in *v1alpha4.PacketMachineTemplateSpec, out *PacketMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(in *v1alpha4.PacketMachineTemplateSpec, out *PacketMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(in, out, s)
}
