//go:build !ignore_autogenerated_core_v1alpha3
// +build !ignore_autogenerated_core_v1alpha3

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.25.0. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api-provider-packet/api/v1beta1"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PacketCluster)(nil), (*v1beta1.PacketCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketCluster_To_v1beta1_PacketCluster(a.(*PacketCluster), b.(*v1beta1.PacketCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketCluster)(nil), (*PacketCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketCluster_To_v1alpha3_PacketCluster(a.(*v1beta1.PacketCluster), b.(*PacketCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketClusterList)(nil), (*v1beta1.PacketClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketClusterList_To_v1beta1_PacketClusterList(a.(*PacketClusterList), b.(*v1beta1.PacketClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketClusterList)(nil), (*PacketClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketClusterList_To_v1alpha3_PacketClusterList(a.(*v1beta1.PacketClusterList), b.(*PacketClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketClusterSpec)(nil), (*v1beta1.PacketClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketClusterSpec_To_v1beta1_PacketClusterSpec(a.(*PacketClusterSpec), b.(*v1beta1.PacketClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketClusterSpec)(nil), (*PacketClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(a.(*v1beta1.PacketClusterSpec), b.(*PacketClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketClusterStatus)(nil), (*v1beta1.PacketClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketClusterStatus_To_v1beta1_PacketClusterStatus(a.(*PacketClusterStatus), b.(*v1beta1.PacketClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachine)(nil), (*v1beta1.PacketMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachine_To_v1beta1_PacketMachine(a.(*PacketMachine), b.(*v1beta1.PacketMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketMachine)(nil), (*PacketMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachine_To_v1alpha3_PacketMachine(a.(*v1beta1.PacketMachine), b.(*PacketMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineList)(nil), (*v1beta1.PacketMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineList_To_v1beta1_PacketMachineList(a.(*PacketMachineList), b.(*v1beta1.PacketMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketMachineList)(nil), (*PacketMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineList_To_v1alpha3_PacketMachineList(a.(*v1beta1.PacketMachineList), b.(*PacketMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplate)(nil), (*v1beta1.PacketMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplate_To_v1beta1_PacketMachineTemplate(a.(*PacketMachineTemplate), b.(*v1beta1.PacketMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketMachineTemplate)(nil), (*PacketMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(a.(*v1beta1.PacketMachineTemplate), b.(*PacketMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplateList)(nil), (*v1beta1.PacketMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplateList_To_v1beta1_PacketMachineTemplateList(a.(*PacketMachineTemplateList), b.(*v1beta1.PacketMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketMachineTemplateList)(nil), (*PacketMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(a.(*v1beta1.PacketMachineTemplateList), b.(*PacketMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplateResource)(nil), (*v1beta1.PacketMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplateResource_To_v1beta1_PacketMachineTemplateResource(a.(*PacketMachineTemplateResource), b.(*v1beta1.PacketMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketMachineTemplateResource)(nil), (*PacketMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(a.(*v1beta1.PacketMachineTemplateResource), b.(*PacketMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PacketMachineTemplateSpec)(nil), (*v1beta1.PacketMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineTemplateSpec_To_v1beta1_PacketMachineTemplateSpec(a.(*PacketMachineTemplateSpec), b.(*v1beta1.PacketMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PacketMachineTemplateSpec)(nil), (*PacketMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(a.(*v1beta1.PacketMachineTemplateSpec), b.(*PacketMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*PacketMachineSpec)(nil), (*v1beta1.PacketMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineSpec_To_v1beta1_PacketMachineSpec(a.(*PacketMachineSpec), b.(*v1beta1.PacketMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*PacketMachineStatus)(nil), (*v1beta1.PacketMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_PacketMachineStatus_To_v1beta1_PacketMachineStatus(a.(*PacketMachineStatus), b.(*v1beta1.PacketMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.PacketClusterStatus)(nil), (*PacketClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketClusterStatus_To_v1alpha3_PacketClusterStatus(a.(*v1beta1.PacketClusterStatus), b.(*PacketClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.PacketMachineSpec)(nil), (*PacketMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(a.(*v1beta1.PacketMachineSpec), b.(*PacketMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.PacketMachineStatus)(nil), (*PacketMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PacketMachineStatus_To_v1alpha3_PacketMachineStatus(a.(*v1beta1.PacketMachineStatus), b.(*PacketMachineStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_PacketCluster_To_v1beta1_PacketCluster(in *PacketCluster, out *v1beta1.PacketCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_PacketClusterSpec_To_v1beta1_PacketClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_PacketClusterStatus_To_v1beta1_PacketClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketCluster_To_v1beta1_PacketCluster is an autogenerated conversion function.
func Convert_v1alpha3_PacketCluster_To_v1beta1_PacketCluster(in *PacketCluster, out *v1beta1.PacketCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketCluster_To_v1beta1_PacketCluster(in, out, s)
}

func autoConvert_v1beta1_PacketCluster_To_v1alpha3_PacketCluster(in *v1beta1.PacketCluster, out *PacketCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PacketClusterStatus_To_v1alpha3_PacketClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_PacketCluster_To_v1alpha3_PacketCluster is an autogenerated conversion function.
func Convert_v1beta1_PacketCluster_To_v1alpha3_PacketCluster(in *v1beta1.PacketCluster, out *PacketCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketCluster_To_v1alpha3_PacketCluster(in, out, s)
}

func autoConvert_v1alpha3_PacketClusterList_To_v1beta1_PacketClusterList(in *PacketClusterList, out *v1beta1.PacketClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.PacketCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_PacketCluster_To_v1beta1_PacketCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_PacketClusterList_To_v1beta1_PacketClusterList is an autogenerated conversion function.
func Convert_v1alpha3_PacketClusterList_To_v1beta1_PacketClusterList(in *PacketClusterList, out *v1beta1.PacketClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketClusterList_To_v1beta1_PacketClusterList(in, out, s)
}

func autoConvert_v1beta1_PacketClusterList_To_v1alpha3_PacketClusterList(in *v1beta1.PacketClusterList, out *PacketClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacketCluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_PacketCluster_To_v1alpha3_PacketCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_PacketClusterList_To_v1alpha3_PacketClusterList is an autogenerated conversion function.
func Convert_v1beta1_PacketClusterList_To_v1alpha3_PacketClusterList(in *v1beta1.PacketClusterList, out *PacketClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketClusterList_To_v1alpha3_PacketClusterList(in, out, s)
}

func autoConvert_v1alpha3_PacketClusterSpec_To_v1beta1_PacketClusterSpec(in *PacketClusterSpec, out *v1beta1.PacketClusterSpec, s conversion.Scope) error {
	out.ProjectID = in.ProjectID
	out.Facility = in.Facility
	if err := apiv1alpha3.Convert_v1alpha3_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.VIPManager = v1beta1.VIPManagerType(in.VIPManager)
	return nil
}

// Convert_v1alpha3_PacketClusterSpec_To_v1beta1_PacketClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_PacketClusterSpec_To_v1beta1_PacketClusterSpec(in *PacketClusterSpec, out *v1beta1.PacketClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketClusterSpec_To_v1beta1_PacketClusterSpec(in, out, s)
}

func autoConvert_v1beta1_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(in *v1beta1.PacketClusterSpec, out *PacketClusterSpec, s conversion.Scope) error {
	out.ProjectID = in.ProjectID
	out.Facility = in.Facility
	if err := apiv1alpha3.Convert_v1beta1_APIEndpoint_To_v1alpha3_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.VIPManager = VIPManagerType(in.VIPManager)
	return nil
}

// Convert_v1beta1_PacketClusterSpec_To_v1alpha3_PacketClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(in *v1beta1.PacketClusterSpec, out *PacketClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketClusterSpec_To_v1alpha3_PacketClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_PacketClusterStatus_To_v1beta1_PacketClusterStatus(in *PacketClusterStatus, out *v1beta1.PacketClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha3_PacketClusterStatus_To_v1beta1_PacketClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_PacketClusterStatus_To_v1beta1_PacketClusterStatus(in *PacketClusterStatus, out *v1beta1.PacketClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketClusterStatus_To_v1beta1_PacketClusterStatus(in, out, s)
}

func autoConvert_v1beta1_PacketClusterStatus_To_v1alpha3_PacketClusterStatus(in *v1beta1.PacketClusterStatus, out *PacketClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	// WARNING: in.Conditions requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_PacketMachine_To_v1beta1_PacketMachine(in *PacketMachine, out *v1beta1.PacketMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_PacketMachineSpec_To_v1beta1_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_PacketMachineStatus_To_v1beta1_PacketMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachine_To_v1beta1_PacketMachine is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachine_To_v1beta1_PacketMachine(in *PacketMachine, out *v1beta1.PacketMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachine_To_v1beta1_PacketMachine(in, out, s)
}

func autoConvert_v1beta1_PacketMachine_To_v1alpha3_PacketMachine(in *v1beta1.PacketMachine, out *PacketMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PacketMachineStatus_To_v1alpha3_PacketMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_PacketMachine_To_v1alpha3_PacketMachine is an autogenerated conversion function.
func Convert_v1beta1_PacketMachine_To_v1alpha3_PacketMachine(in *v1beta1.PacketMachine, out *PacketMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketMachine_To_v1alpha3_PacketMachine(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineList_To_v1beta1_PacketMachineList(in *PacketMachineList, out *v1beta1.PacketMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.PacketMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_PacketMachine_To_v1beta1_PacketMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_PacketMachineList_To_v1beta1_PacketMachineList is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineList_To_v1beta1_PacketMachineList(in *PacketMachineList, out *v1beta1.PacketMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineList_To_v1beta1_PacketMachineList(in, out, s)
}

func autoConvert_v1beta1_PacketMachineList_To_v1alpha3_PacketMachineList(in *v1beta1.PacketMachineList, out *PacketMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacketMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_PacketMachine_To_v1alpha3_PacketMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_PacketMachineList_To_v1alpha3_PacketMachineList is an autogenerated conversion function.
func Convert_v1beta1_PacketMachineList_To_v1alpha3_PacketMachineList(in *v1beta1.PacketMachineList, out *PacketMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketMachineList_To_v1alpha3_PacketMachineList(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineSpec_To_v1beta1_PacketMachineSpec(in *PacketMachineSpec, out *v1beta1.PacketMachineSpec, s conversion.Scope) error {
	out.OS = in.OS
	out.BillingCycle = in.BillingCycle
	out.MachineType = in.MachineType
	// WARNING: in.SshKeys requires manual conversion: does not exist in peer-type
	out.Facility = in.Facility
	out.IPXEUrl = in.IPXEUrl
	out.HardwareReservationID = in.HardwareReservationID
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.Tags = *(*v1beta1.Tags)(unsafe.Pointer(&in.Tags))
	return nil
}

func autoConvert_v1beta1_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(in *v1beta1.PacketMachineSpec, out *PacketMachineSpec, s conversion.Scope) error {
	out.OS = in.OS
	out.BillingCycle = in.BillingCycle
	out.MachineType = in.MachineType
	// WARNING: in.SSHKeys requires manual conversion: does not exist in peer-type
	out.Facility = in.Facility
	out.IPXEUrl = in.IPXEUrl
	out.HardwareReservationID = in.HardwareReservationID
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.Tags = *(*Tags)(unsafe.Pointer(&in.Tags))
	return nil
}

func autoConvert_v1alpha3_PacketMachineStatus_To_v1beta1_PacketMachineStatus(in *PacketMachineStatus, out *v1beta1.PacketMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*v1beta1.PacketResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_PacketMachineStatus_To_v1alpha3_PacketMachineStatus(in *v1beta1.PacketMachineStatus, out *PacketMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*PacketResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	// WARNING: in.Conditions requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_PacketMachineTemplate_To_v1beta1_PacketMachineTemplate(in *PacketMachineTemplate, out *v1beta1.PacketMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_PacketMachineTemplateSpec_To_v1beta1_PacketMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplate_To_v1beta1_PacketMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplate_To_v1beta1_PacketMachineTemplate(in *PacketMachineTemplate, out *v1beta1.PacketMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplate_To_v1beta1_PacketMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(in *v1beta1.PacketMachineTemplate, out *PacketMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(in *v1beta1.PacketMachineTemplate, out *PacketMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineTemplateList_To_v1beta1_PacketMachineTemplateList(in *PacketMachineTemplateList, out *v1beta1.PacketMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.PacketMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_PacketMachineTemplate_To_v1beta1_PacketMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplateList_To_v1beta1_PacketMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplateList_To_v1beta1_PacketMachineTemplateList(in *PacketMachineTemplateList, out *v1beta1.PacketMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplateList_To_v1beta1_PacketMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(in *v1beta1.PacketMachineTemplateList, out *PacketMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacketMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_PacketMachineTemplate_To_v1alpha3_PacketMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(in *v1beta1.PacketMachineTemplateList, out *PacketMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketMachineTemplateList_To_v1alpha3_PacketMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineTemplateResource_To_v1beta1_PacketMachineTemplateResource(in *PacketMachineTemplateResource, out *v1beta1.PacketMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_PacketMachineSpec_To_v1beta1_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplateResource_To_v1beta1_PacketMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplateResource_To_v1beta1_PacketMachineTemplateResource(in *PacketMachineTemplateResource, out *v1beta1.PacketMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplateResource_To_v1beta1_PacketMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(in *v1beta1.PacketMachineTemplateResource, out *PacketMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_PacketMachineSpec_To_v1alpha3_PacketMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(in *v1beta1.PacketMachineTemplateResource, out *PacketMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_PacketMachineTemplateSpec_To_v1beta1_PacketMachineTemplateSpec(in *PacketMachineTemplateSpec, out *v1beta1.PacketMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_PacketMachineTemplateResource_To_v1beta1_PacketMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_PacketMachineTemplateSpec_To_v1beta1_PacketMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_PacketMachineTemplateSpec_To_v1beta1_PacketMachineTemplateSpec(in *PacketMachineTemplateSpec, out *v1beta1.PacketMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_PacketMachineTemplateSpec_To_v1beta1_PacketMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(in *v1beta1.PacketMachineTemplateSpec, out *PacketMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_PacketMachineTemplateResource_To_v1alpha3_PacketMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(in *v1beta1.PacketMachineTemplateSpec, out *PacketMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PacketMachineTemplateSpec_To_v1alpha3_PacketMachineTemplateSpec(in, out, s)
}
